# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("EnrichPost", {
  # tests for EnrichPost
  # base path: https://toppgene.cchmc.org/API
  # Perform Functional Enrichment
  # @param enrichment_request EnrichmentRequest JSON Payload of Entrez genes and which categories needed.
  # @param pretty character Optional. If `true` ToppGene will indent output (optional)
  # @param as character Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format. (optional)
  # @return [EnrichmentResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("LookupPost", {
  # tests for LookupPost
  # base path: https://toppgene.cchmc.org/API
  # Convert genes to Human Entrez IDs
  # @param lookup_request LookupRequest 
  # @param pretty character Optional. If `true` ToppGene will indent output (optional)
  # @param as character Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format. (optional)
  # @return [LookupResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
