# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnrichmentResponseAnnotationsInner")

model_instance <- EnrichmentResponseAnnotationsInner$new()

test_that("Category", {
  # tests for the property `Category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Category`, "EXPECTED_RESULT")
})

test_that("ID", {
  # tests for the property `ID` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ID`, "EXPECTED_RESULT")
})

test_that("Name", {
  # tests for the property `Name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Name`, "EXPECTED_RESULT")
})

test_that("PValue", {
  # tests for the property `PValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`PValue`, "EXPECTED_RESULT")
})

test_that("QValueFDRBH", {
  # tests for the property `QValueFDRBH` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`QValueFDRBH`, "EXPECTED_RESULT")
})

test_that("QValueFDRBY", {
  # tests for the property `QValueFDRBY` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`QValueFDRBY`, "EXPECTED_RESULT")
})

test_that("QValueBonferroni", {
  # tests for the property `QValueBonferroni` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`QValueBonferroni`, "EXPECTED_RESULT")
})

test_that("TotalGenes", {
  # tests for the property `TotalGenes` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`TotalGenes`, "EXPECTED_RESULT")
})

test_that("GenesInTerm", {
  # tests for the property `GenesInTerm` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`GenesInTerm`, "EXPECTED_RESULT")
})

test_that("GenesInQuery", {
  # tests for the property `GenesInQuery` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`GenesInQuery`, "EXPECTED_RESULT")
})

test_that("GenesInTermInQuery", {
  # tests for the property `GenesInTermInQuery` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`GenesInTermInQuery`, "EXPECTED_RESULT")
})

test_that("Source", {
  # tests for the property `Source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Source`, "EXPECTED_RESULT")
})

test_that("URL", {
  # tests for the property `URL` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`URL`, "EXPECTED_RESULT")
})

test_that("Genes", {
  # tests for the property `Genes` (array[EnrichmentResponseAnnotationsInnerGenesInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`Genes`, "EXPECTED_RESULT")
})
