# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnrichmentResponse")

model_instance <- EnrichmentResponse$new()

test_that("Annotations", {
  # tests for the property `Annotations` (array[EnrichmentResponseAnnotationsInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`Annotations`, "EXPECTED_RESULT")
})
