# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnrichmentRequestCategoriesInner")

model_instance <- EnrichmentRequestCategoriesInner$new()

test_that("Type", {
  # tests for the property `Type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Type`, "EXPECTED_RESULT")
})

test_that("PValue", {
  # tests for the property `PValue` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`PValue`, "EXPECTED_RESULT")
})

test_that("MinGenes", {
  # tests for the property `MinGenes` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`MinGenes`, "EXPECTED_RESULT")
})

test_that("MaxGenes", {
  # tests for the property `MaxGenes` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`MaxGenes`, "EXPECTED_RESULT")
})

test_that("MaxResults", {
  # tests for the property `MaxResults` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`MaxResults`, "EXPECTED_RESULT")
})

test_that("Correction", {
  # tests for the property `Correction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Correction`, "EXPECTED_RESULT")
})
