# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnrichmentRequest")

model_instance <- EnrichmentRequest$new()

test_that("Genes", {
  # tests for the property `Genes` (array[integer])
  # A list of Human Entrez ID that need functional enrichment.

  # uncomment below to test the property
  #expect_equal(model.instance$`Genes`, "EXPECTED_RESULT")
})

test_that("Categories", {
  # tests for the property `Categories` (array[EnrichmentRequestCategoriesInner])
  # The Categories list is optional. If omitted, ToppGene will run on all categories with default values. Otherwise, ToppGene will only return the requested categories.

  # uncomment below to test the property
  #expect_equal(model.instance$`Categories`, "EXPECTED_RESULT")
})
