# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LookupResponse")

model_instance <- LookupResponse$new()

test_that("Genes", {
  # tests for the property `Genes` (array[LookupResponseGenesInner])
  # An array of one or more genes. Unresolvable genes are *not* returned. If no genes are found, ToppGene returns &#x60;null&#x60; rather than an empty array. No guarentee is made that the array order matches the input order.

  # uncomment below to test the property
  #expect_equal(model.instance$`Genes`, "EXPECTED_RESULT")
})
