# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LookupRequest")

model_instance <- LookupRequest$new()

test_that("Symbols", {
  # tests for the property `Symbols` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`Symbols`, "EXPECTED_RESULT")
})
