# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EnrichmentResponseAnnotationsInnerGenesInner")

model_instance <- EnrichmentResponseAnnotationsInnerGenesInner$new()

test_that("Entrez", {
  # tests for the property `Entrez` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`Entrez`, "EXPECTED_RESULT")
})

test_that("Symbol", {
  # tests for the property `Symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`Symbol`, "EXPECTED_RESULT")
})
