# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LookupResponseGenesInner")

model_instance <- LookupResponseGenesInner$new()

test_that("OfficialSymbol", {
  # tests for the property `OfficialSymbol` (character)
  # The official HGNC gene symbol.

  # uncomment below to test the property
  #expect_equal(model.instance$`OfficialSymbol`, "EXPECTED_RESULT")
})

test_that("Entrez", {
  # tests for the property `Entrez` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`Entrez`, "EXPECTED_RESULT")
})

test_that("SubmittedSymbol", {
  # tests for the property `SubmittedSymbol` (character)
  # The symbol as provided in the request body. Useful to reconnect results to requests.

  # uncomment below to test the property
  #expect_equal(model.instance$`SubmittedSymbol`, "EXPECTED_RESULT")
})
