#' ToppGene API
#'
#' ToppGene API
#'
#' The version of the OpenAPI document: 1.0.0
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Default operations
#' @description DefaultApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  EnrichPost  ####################
#'
#' library(openapi)
#' var_enrichment_request <- EnrichmentRequest$new(c(123), c(EnrichmentRequest_Categories_inner$new("GeneOntologyMolecularFunction", 123, 123, 123, 123, "None"))) # EnrichmentRequest | JSON Payload of Entrez genes and which categories needed.
#' var_pretty <- "pretty_example" # character | Optional. If `true` ToppGene will indent output (Optional)
#' var_as <- "as_example" # character | Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format. (Optional)
#'
#' #Perform Functional Enrichment
#' api_instance <- DefaultApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$EnrichPost(var_enrichment_request, pretty = var_pretty, as = var_asdata_file = "result.txt")
#' result <- api_instance$EnrichPost(var_enrichment_request, pretty = var_pretty, as = var_as)
#' dput(result)
#'
#'
#' ####################  LookupPost  ####################
#'
#' library(openapi)
#' var_lookup_request <- LookupRequest$new(c("Symbols_example")) # LookupRequest | 
#' var_pretty <- "pretty_example" # character | Optional. If `true` ToppGene will indent output (Optional)
#' var_as <- "as_example" # character | Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format. (Optional)
#'
#' #Convert genes to Human Entrez IDs
#' api_instance <- DefaultApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$LookupPost(var_lookup_request, pretty = var_pretty, as = var_asdata_file = "result.txt")
#' result <- api_instance$LookupPost(var_lookup_request, pretty = var_pretty, as = var_as)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
DefaultApi <- R6::R6Class(
  "DefaultApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new DefaultApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Perform Functional Enrichment
    #'
    #' @param enrichment_request JSON Payload of Entrez genes and which categories needed.
    #' @param pretty (optional) Optional. If `true` ToppGene will indent output
    #' @param as (optional) Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return EnrichmentResponse
    EnrichPost = function(enrichment_request, pretty = NULL, as = NULL, data_file = NULL, ...) {
      local_var_response <- self$EnrichPostWithHttpInfo(enrichment_request, pretty, as, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },

    #' @description
    #' Perform Functional Enrichment
    #'
    #' @param enrichment_request JSON Payload of Entrez genes and which categories needed.
    #' @param pretty (optional) Optional. If `true` ToppGene will indent output
    #' @param as (optional) Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (EnrichmentResponse) with additional information such as HTTP status code, headers
    EnrichPostWithHttpInfo = function(enrichment_request, pretty = NULL, as = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`enrichment_request`)) {
        stop("Missing required parameter `enrichment_request`.")
      }




      query_params[["pretty"]] <- `pretty`

      if (!is.null(`as`) && !(`as` %in% c("json", "xml"))) {
        stop("Invalid value for as when calling DefaultApi$EnrichPost. Must be [json, xml].")
      }
      query_params[["as"]] <- `as`

      if (!is.null(`enrichment_request`)) {
        local_var_body <- `enrichment_request`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/enrich"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "EnrichmentResponse", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },

    #' @description
    #' Convert genes to Human Entrez IDs
    #'
    #' @param lookup_request 
    #' @param pretty (optional) Optional. If `true` ToppGene will indent output
    #' @param as (optional) Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return LookupResponse
    LookupPost = function(lookup_request, pretty = NULL, as = NULL, data_file = NULL, ...) {
      local_var_response <- self$LookupPostWithHttpInfo(lookup_request, pretty, as, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },

    #' @description
    #' Convert genes to Human Entrez IDs
    #'
    #' @param lookup_request 
    #' @param pretty (optional) Optional. If `true` ToppGene will indent output
    #' @param as (optional) Override defaults and/or HTTP request headers for return format. The XML result is not described in this definition file, but it is substantially similar to the JSON format.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (LookupResponse) with additional information such as HTTP status code, headers
    LookupPostWithHttpInfo = function(lookup_request, pretty = NULL, as = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`lookup_request`)) {
        stop("Missing required parameter `lookup_request`.")
      }




      query_params[["pretty"]] <- `pretty`

      if (!is.null(`as`) && !(`as` %in% c("json", "xml"))) {
        stop("Invalid value for as when calling DefaultApi$LookupPost. Must be [json, xml].")
      }
      query_params[["as"]] <- `as`

      if (!is.null(`lookup_request`)) {
        local_var_body <- `lookup_request`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/lookup"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "LookupResponse", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
